branches:
  only:
    - master
language: python
python:
- '3.5'
cache: pip
install:
- pip install --upgrade pip
- pip install --upgrade -r requirements.txt
script: python -m unittest discover -s tests
